### ISSUE TITLE
Comply with the new Jenkins Security Settings

### ISSUE THREAD

**Issue by santostiago** [web-innovate/bootstraped-multi-test-results-report#12]
In the newest versions of Jenkins, the page is shown in plain html, because of Jenkins' new security policy.
Please create a fix for this :)

**Comment by BogdanLivadariu** [comment]
as a temporary solution you could do this :
![image](https://cloud.githubusercontent.com/assets/8307102/13374019/d713a7f0-dd80-11e5-9530-b9504503c126.png)

but after you restart jenkins, you'll have to do it again.

I managed to host the js /css / etc files locally, but jenkins does not allow js execution inside, so this is at the moment the thing you will have to do in allowing jenkins to execute scripts.

hosting js /css files locally will end-up in 1.4.8 I hope :)

**Comment by BogdanLivadariu** [comment]
tweak your `/etc/sysconfig/jenkins` file to add an extra property
`-Dhudson.model.DirectoryBrowserSupport.CSP=""`
so it might look similar to 

```
JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"\""
```

**Comment by BogdanLivadariu** [comment]
from `2.0.1` plugin will comply with the security, no more tweaking should be required :)
