### ISSUE TITLE
Doesn't save file include pattern

### ISSUE THREAD

**Issue by CyborTronik** [web-innovate/bootstraped-multi-test-results-report#17]
Trying to add file include pattern, then press apply&save. Open the configuration again and in 'Advanced' section everything is empty.
The same for folder.

**Comment by BogdanLivadariu** [comment]
@CyborTronik 
[this should be fixed in 1.4.7](
https://github.com/web-innovate/bootstraped-multi-test-results-report/pull/13)

**Comment by CyborTronik** [comment]
Works nicely.
Thank you for fast fix
