### ISSUE TITLE
Problem putting unstable project when test fails

### ISSUE THREAD

**Issue by pedrodelgado81** [web-innovate/bootstraped-multi-test-results-report#27]
When one test fails, set the project to "unstable" state doesn't work. The problem is that *ReportBuilder.java (in my case TestNgReportBuilder.java) there is this conditional (line 116):
` if (ts.getTotalClassesFailed() > 1 || ts.getTotalClassesSkipped() > 1) {
                return false;
            }`
The comparission must be  
`if (ts.getTotalClassesFailed() => 1 || ts.getTotalClassesSkipped() => 1) {
                return false;
  }`

If more thant one test fails, works well, but with only one failing test doesn't.

**Comment by BogdanLivadariu** [comment]
@pedrodelgado81 this issue should get fixed with the next version 1.4.10 that I plan to release in the next hour
https://github.com/web-innovate/bootstraped-multi-test-results-report/pull/29

**Comment by pedrodelgado81** [comment]
Resolved in 1.4.10

**Comment by BogdanLivadariu** [comment]
@pedrodelgado81 please close the issue
