### ISSUE TITLE
CUCUMBER: No information about tags in the report

### ISSUE THREAD

**Issue by Vovanchik** [web-innovate/bootstraped-multi-test-results-report#33]
Hello,

I am using cucumber-js framework which returns tags in the report. Is it possible to add such information as well.
[report_example.txt](https://github.com/web-innovate/bootstraped-multi-test-results-report/files/268539/report_example.txt)

Here is the json_report_example.txt

**Comment by BogdanLivadariu** [comment]
@Vovanchik the improvement to display tags for scenarios has been pushed in, and will be available in the next release 1.4.14 I guess

**Comment by BogdanLivadariu** [comment]
@Vovanchik 1.4.14 has just been released, your fix for build passing when undefined steps are present + the two improvements, to show the tags for scenarios and adding a proper color for the undefined steps are in.

you could wait for the autoupdate, or you could just download the HPI & install it manually from here:
http://repo.jenkins-ci.org/public/com/github/bogdanlivadariu/bootstraped-multi-test-results-report/1.4.14/

**Comment by Vovanchik** [comment]
Thank you. Will check and let you know about results.
