### ISSUE TITLE
Support of JUnit <testsuites> root tag? 

### ISSUE THREAD

**Issue by bagage** [web-innovate/bootstraped-multi-test-results-report#35]
After investigating why it did not work (thanks @BogdanLivadariu), I finally found that `bootstraped-multi-test-results-report` seems not to support JUnit reports that contains several suites, for instance:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite errors="0" failures="0" tests="1" name="Suite 1" time="0" >
    <testcase name="Test 1.1" time="0"/>
  </testsuite>
  <testsuite errors="0" failures="0" tests="1" name="Suite 2" time="0" >
    <testcase name="Test 2.1" time="0"/>
  </testsuite>
</testsuites>
```

I believe that this should work though, according to [JUnit Schema XSD](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd). I may implement support of this if you agree with it; but I prefer rather to ask before implementing it ;).

**Comment by BogdanLivadariu** [comment]
@bagage it does not support this sort of stuff :) it would be nice though 

don't want to come with excuses, but I built this in a short period of time, without giving thought on what users might want to have in their reports, I only thought on what I want to have in the reports :)

I will add this to my TODO list

p.s How fast do you want this to be in ?:D

**Comment by bagage** [comment]
@BogdanLivadariu I can implement it myself actually (I believe). But I just wanted to be sure that you are OK to merge it upstream in the first place to ensure it's worth it :smile:

**Comment by BogdanLivadariu** [comment]
@bagage innovation is always on my radar,

I think it is a good thing to see ideas happen here.

do the code, raise the PR, and we'll review it, once that is done I'll merge it and release a new version, so you could play with 💃

**Comment by BogdanLivadariu** [comment]
@bagage I guess we can close this, thanks to you :)
