### ISSUE TITLE
CUCUMBER: Mark scenario as passed if you have undefined steps, but all other passed

### ISSUE THREAD

**Issue by Vovanchik** [web-innovate/bootstraped-multi-test-results-report#49]
As we disсussed in issue #32 it will be good to have an option in the plugin config, that you can tick
so that undefined steps are ignored, and in a scenario if you have undefined steps, scenario will be marked as passed.

**Comment by BogdanLivadariu** [comment]
@Vovanchik  1.4.16 version of the plugin should have the enhancement in

**Comment by Vovanchik** [comment]
Thank you. Will update and provide you feedback.

**Comment by Vovanchik** [comment]
Updated plugin to the latest  1.4.16 version, but still don't see an option to mark scenario as PASSED if there are some undefined steps and no failed steps.

Could you please provide an info when it will be ready?

**Comment by BogdanLivadariu** [comment]
![image](https://cloud.githubusercontent.com/assets/8307102/16833433/0584ecc2-49b8-11e6-9423-44598e0767e9.png)

@Vovanchik  you should see it just above

**Comment by Vovanchik** [comment]
Hello,

For scenario everything look's good and work as expected.

In this case I think feature must be marked as PASSED as well. For details see:
![failed scenario](https://cloud.githubusercontent.com/assets/162919/16868190/eeccc55a-4a7e-11e6-9b53-77ce0e1993ab.png)

After testing I discovered a bug - that after setting checkbox in configuration near: "Undefined steps will not be taken into ..." it is stored but after reopening checkbox is cleared.

**Comment by BogdanLivadariu** [comment]
@Vovanchik right, will try to fix it ASAP :D

**Comment by BogdanLivadariu** [comment]
@Vovanchik  [1.4.17](http://repo.jenkins-ci.org/releases/com/github/bogdanlivadariu/bootstraped-multi-test-results-report/1.4.17/) version of the plugin should have the bugfix in

**Comment by Vovanchik** [comment]
Look's really good right now. Thank you for your help.
