### ISSUE TITLE
Faulty behavior of plugin settings

### ISSUE THREAD

**Issue by Vovanchik** [web-innovate/bootstraped-multi-test-results-report#53]
When you set parameter "Undefined steps will not be taken into consideration when evaluating the scenario status" and click on Apply than this parameter is not stored after page is re-loaded.

**Steps to reproduce:**
1. Open plugin settings
2. Set "Undefined steps will not be taken into consideration when evaluating the scenario status"
3. Refresh page
**Result:**
Configuration not stored and checkbox near "Undefined steps will not be taken into consideration when evaluating the scenario status" cleared

**Expected result:**
After re-login configuration must be stored and checkbox set near "Undefined steps will not be taken into consideration when evaluating the scenario status"

**Workaround:**
Instead of Apply use Save. Configuration is not shown on UI, but stored in configuration file.

**Comment by BogdanLivadariu** [comment]
@Vovanchik is this only happening for that specific checkbox ?

or it happens for the rest as well ?

**Comment by Vovanchik** [comment]
It happens only on this specific checkbox: "Undefined steps will not be taken into consideration when evaluating the scenario status"

**Comment by BogdanLivadariu** [comment]
@Vovanchik you are right, pushing the fix in [here](https://github.com/web-innovate/bootstraped-multi-test-results-report/pull/54)

**Comment by Vovanchik** [comment]
Cool. Waiting for new release than :)

**Comment by BogdanLivadariu** [comment]
@Vovanchik  [1.4.18](http://repo.jenkins-ci.org/releases/com/github/bogdanlivadariu/bootstraped-multi-test-results-report/1.4.18/) version of the plugin should have the bugfix in, once the it deploys :dancer:

**Comment by BogdanLivadariu** [comment]
@Vovanchik any updates ? can you close the issue if the issue is fixed ?

**Comment by Vovanchik** [comment]
Only yesterday plugin was available for upgrade. Will check it today-tomorrow and close the issue. Thank you for quick fix.

**Comment by Vovanchik** [comment]
Re-tested plugin on my builds. Everything work's as expected.

Thank you.
