### ISSUE TITLE
maven artifacts are not usable

### ISSUE THREAD

**Issue by dantran** [web-innovate/bootstraped-multi-test-results-report#69]
all the poms have version set at ${project.version}

maven complains this
com.github.bogdanlivadariu:testng-reporting-handlebars:jar:1.0.8: Failure to find   com.github.bogdanlivadariu:bootstraped-multi-test-results-report-reactor-parent:pom:${parent.version} in http://ap-sc.lss.emc.com:8081/artifactory/public was cached in the local repository, resolution will not be reattempted until the update interval of brs has elapsed or updates are forced -> [Help 1]

notice the ${parent.version} looks like you deploy maven incorrectly

File  at

http://central.maven.org/maven2/com/github/bogdanlivadariu/bootstraped-multi-test-results-report-reactor-parent/1.4.20/bootstraped-multi-test-results-report-reactor-parent-1.4.20.pom

this pom is invalid, there fore i can't use it 
its version is set at ${project.version}

**Comment by BogdanLivadariu** [comment]
@dantran latest code, should have this problem fixed , can you confirm ?

**Comment by dantran** [comment]
it works. Thanks
