### ISSUE TITLE
Pipeline integration

### ISSUE THREAD

**Issue by vermut** [web-innovate/bootstraped-multi-test-results-report#70]
I cannot find a way to call this from Pipeline's Jenkinsfile. Please advise

**Comment by BogdanLivadariu** [comment]
At the moment the plugin does not support usage in pipeline, but I'll try to fit this request into my spare time

**Comment by BogdanLivadariu** [comment]
plan to make pipeline usage available in #71 
at the moment only testNG reporter is supported, hope to bring the rest up to speed as well

**Comment by vermut** [comment]
Wow. Thanks. Looking forward to it. We are  mostly interested in rspec

**Comment by BogdanLivadariu** [comment]
will try to make it tick in 2.0.1, in the mean time can you share a xml file to see if it really works ?

**Comment by BogdanLivadariu** [comment]
rspec module as well as the rest, will have pipeline support from `2.0.1` version
@vermut check #72 for how to use pipeline support for rspec, until I update the readme sections :)
