### ISSUE TITLE
Cucumber duration isn't showing up

### ISSUE THREAD

**Issue by Muschasgrazias** [web-innovate/bootstraped-multi-test-results-report#80]
Hi,

I tried to use your plugin with an official cucumber json file:
[docs](https://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter) 
one feature, one passing scenario, one failing scenario `@spawn` was the one I used.
But in the report the duration is always 0.

Kind regards

**Comment by BogdanLivadariu** [comment]
@Muschasgrazias I'll look into it
sounds like a great catch :)
I'll get back to you with the fix

**Comment by BogdanLivadariu** [comment]
@Muschasgrazias 
I have never tried having `1` in the duration field :D
the values in that report I think they were manually changed.

having just `1`  there would mean to display the `nanoSeconds` which is not supported in the plugin.

give it a spin with a real generated report your framework dumps and you should not have any problems
